# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-29 18:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('branchname', models.CharField(max_length=30, null=True)),
                ('occupation', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=30)),
                ('feedback', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=15, null=True)),
                ('semester', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)])),
                ('file', models.FileField(null=True, upload_to='notes/')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=20)),
                ('semister', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('files', models.FileField(null=True, upload_to='file/')),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=20)),
                ('file', models.FileField(null=True, upload_to='syllabus/')),
            ],
        ),
    ]
