name: Deploy Backend

on: workflow_dispatch

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: amitkarmakar13
          password: dckr_pat_X_HznS8Iv13Pascyy8dPjo8xxYI

      - name: Build backend and push
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./
          # Note: tags has to be all lower-case
          file: ./backend/blueback/Dockerfile
          tags: |
            collegepapers:backend
          push: true
          buildkitd-flags: --debug